resources:
 builds:
   - build: javaAppBuild
     type: Jenkins
     connection: Spaceworkz
     source: UBSTest

stages:
  - stage: Build
    jobs:
     - deployment: Deploy
       displayName: Some name
       pool:
        name: default
       strategy:
        runOnce:
          deploy:
            steps:
              - powershell: |
                  ls $(Pipeline.Workspace)/